name: build

on: [workflow_dispatch]

jobs: 
  everything:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v2
      - name: Run script
        shell: bash
        run: |
         chmod +x ./build-scripts/ci-build.sh
         ./build-scripts/ci-build.sh 
      - uses: actions/upload-artifact@v3
        with:
          name: lamassu-server.tar.gz
          path: ./lamassu-server.tar.gz
